POST http://localhost:8080/api/inventory
# POST http://catalog-coolstore-test.apps.cluster-6141.6141.sandbox1484.opentlc.com/api/products
Content-Type: application/json

[
    {
        "itemId": "1",
        "location": "Boston1",
        "link": "http://www.yahoo.com/",
        "quantity": 10
    },
    {
        "itemId": "2",
        "location": "New York2",
        "link": "http://www.google.com/",
        "quantity": 20
    }
]

###

GET http://localhost:8080/api/inventory